---
title: "species-selection"
author: "jt-miller"
date: "2023-12-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Some finer grain selection on species (if possible)

```{r}
library(data.table)
```

```{r}
hpg <- fread("/home/jt-miller/Gurlab/sliding-phenology/data/processed/high-coverage-plant-data.csv")
```

```{r}
# plant taxa
grid_holder_p <- list()
gid_p_v <- unique(hpg$GID)
for(i in 1:length(unique(hbg$GID))){
  grid_holder_p[[i]] <- hpg[GID == gid_p_v[[i]],]
}

# Function that uses a for-loop to create the decadal subsets
decadal_subsetter <- function(dataset, start_year, end_year, bin_size){
  decadal_subsets <- list() # empty storage list
for(i in start_year:(end_year - bin_size)){
  end <- i + bin_size # Our end condition 
  subset_data <- dataset[year >= i & year <= end, ] # Subsets the data into bins on a decadal sliding scale
  decadal_subsets[[paste(i, end, sep = "-")]] <- subset_data # Label
}
  return(decadal_subsets)
}

# Set arguments
start_year <- 1950
end_year <- 2023
bin_size <- 10
gids <- c(217, 229, 230, 241)


nested_list_holder_p <- list()
for(i in 1:length(grid_holder_p)){
decadal_subsets <- decadal_subsetter(dataset = grid_holder_p[[i]], # Take the ith grid and do the decadal subsetting  
                  start_year = start_year, 
                  end_year = end_year, 
                  bin_size = bin_size)
nested_list_holder_p[[paste(gids[i], "grid", sep = "-")]] <- decadal_subsets
}
```

```{r}
sample_cell <- nested_list_holder_p[[4]]

test <- rbindlist(sample_cell, idcol = TRUE)

test %>% 
  rename(time_bin = .id) %>% 
  group_by(scientificName) %>% 
  summarize(perc_of_bins_present = n_distinct(time_bin)/(length(unique(time_bin))) * 100) %>% 
  arrange(desc(perc_of_bins_present))

test %>% 
  group_by(scientificName) %>% 
  summarize(count = n()) %>% 
  arrange(desc(count))

test %>% 
  rename(time_bin = .id) %>%  
  group_by(scientificName, time_bin) %>%
  summarize(count = n()) %>% 
  filter(scientificName == "Chaenactis fremontii")
```


```{r}
t <- 1980
hpg_f <- hpg %>% 
  filter(year >= t)
hpg_f %>% 
  group_by(scientificName) %>% 
  summarize(perc_of_years_present = n_distinct(year)/(2023-t) * 100) %>% 
  arrange(desc(perc_of_years_present))
```

Desert Pincushion, *Chaenactis fremontii*
```{r}
sample_cell_f <- list()
for(i in 1:length(sample_cell)){
  data <- sample_cell[[i]]
  data_f <- subset(data, scientificName == "Chaenactis fremontii")
  sample_cell_f[[i]] <- data_f
}


for(w in 1:length(nested_list_holder_p)){
  spatial_ID <- names(nested_list_holder_p[w]) # replace with w
  spatial_bin <- nested_list_holder_p[[w]] # replace with w 
  for(j in 1:length(spatial_bin)){
    named_temporal_bin <- names(spatial_bin[j]) # replace with j
    spatial_temporal_ID <- paste0(spatial_ID, "_", named_temporal_bin)
    temporal_spatial_bin <- spatial_bin[[j]] # replace with j
    temporal_spatial_bin <- subset(temporal_spatial_bin, scientificName %in% c("Chaenactis fremontii", "Abronia villosa", "Encelia farinosa", "Rafinesquia neomexicana"))
    unique_names_in_bin_v <- unique(temporal_spatial_bin$scientificName) # extract a vector of uniq scientific names from bin
    num_of_species <- length(unique_names_in_bin_v)
    subset <- temporal_spatial_bin # rename
    #for(i in 1:length(unique_names_in_bin_v)){
      #named_subset <- temporal_spatial_bin[scientificName %in% unique_names_in_bin_v[i]] # replace with i
       if(nrow(subset) <= 5 | length(unique(subset$doy)) <= 3){
    named_phenometric_summary <- data.table(taxa = "plants", GID = unique(subset$GID), number_of_records = nrow(subset), fiftieth_percentile = NA, fiftieth_var = NA, upper_var_bound = NA, lower_var_bound = NA)
  }else{
    # Using kde1
    subset <- subset[doy >= 0 & doy <= 365]
    kde.sims <- kde1d(x = subset$doy) # est the univariate likelihood kernel density. xmin = 0, xmax = 365
    quant50 <- qkde1d(p = 0.50, obj=kde.sims) # pull out the 50th quantile
    emp.rand.samp <- rkde1d(n = 10000, obj = kde.sims) # use random generation to find variance
    var50 <- var(emp.rand.samp) # calc variance
    
    # Plot + Variance #############################################################################################################
    png(paste0("/home/jt-miller/Gurlab/sliding-phenology/outputs/test_plots/", "sample-annuals", "_", spatial_temporal_ID, ".png"), width = 800, height = 600)
    plot(kde.sims, main = paste0("Plant Community ", " Kernel Density Distribution for Time Bin ", spatial_temporal_ID), xlab = "day of year", xlim = c(0,365))
    abline(v = quant50, col = "red")
    upper_bound <- quant50 + sqrt(var50)
    lower_bound <- quant50 - sqrt(var50)
    # Add error bars
    #segments(x0 = quant50, y0 = lower_boun, x1 = quant50, y1 = upper_bound, col = "blue", lwd = 2)
    abline(v = upper_bound, lty= 'dashed', col = "blue")
    abline(v = lower_bound, lty = 'dashed', col = "blue")
    # Add a legend
    legend("topright", legend = c("Kernel Density", "50th Percentile", "Variance"),
       col = c("black", "red", "blue"), lty = c(1, 1, 2), lwd = c(1, 1, 2), cex = 0.9)
   
     dev.off() 
     # End plot saving ##################################################################################################
    
    named_phenometric_summary <- data.table(taxa = "plants", GID = unique(subset$GID),
                                            number_of_records = nrow(subset), time_bin = named_temporal_bin)
    named_phenometric_summary <- named_phenometric_summary[, fiftieth_percentile := quant50]
    named_phenometric_summary <- named_phenometric_summary[, fiftieth_var := var50]
    named_phenometric_summary <- named_phenometric_summary[, upper_var_bound := upper_bound]
    named_phenometric_summary <- named_phenometric_summary[, lower_var_bound := lower_bound]
    named_phenometric_summary <- named_phenometric_summary[, num_of_species := num_of_species]
  
fwrite(named_phenometric_summary, paste0("/home/jt-miller/Gurlab/sliding-phenology/outputs/test_tables/", "sample_annuals", "_", spatial_temporal_ID, ".csv"))

} # End of else statement
    name <- gsub(",", "", unique(subset$scientificName)) # Fix some file naming shennanigans
    name <- gsub(" ", "-", name) # ""
    fwrite(named_phenometric_summary, paste0("/home/jt-miller/Gurlab/sliding-phenology/outputs/test_tables/", "sample_annuals", "_", spatial_temporal_ID, ".csv"))
    #} # end of i loop
  } # end of j loop
} # end of w loop

```

