---
title: "phenessing"
author: "jt-miller"
date: "2023-11-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Phennessing the Data
```{r}
library(data.table)
library(phenesse)
library(sf)
library(raster)
library(dplyr)
library(ggplot2)
```
Read in the Data 
```{r}
fld <- fread("/home/jt-miller/Gurlab/sliding-phenology/data/processed/sonoran-flowering-temporal-labeled-data.csv")
bd <- fread("/home/jt-miller/Gurlab/sliding-phenology/data/processed/sonoran-bee-temporal-labeled-data.csv")
# Bring in Ecoregion shapefiles 
na_ecoregions_3 <- sf::read_sf("/home/jt-miller/Gurlab/sliding-phenology/data/raw/shapefiles/NA-level-3-epa-ecoregions/NA_CEC_Eco_Level3.shp")
# Filter for just the Sonoran Desert & Mojave
sonoran_shp <- subset(na_ecoregions_3, na_ecoregions_3$NA_L3NAME == "Sonoran Desert")
```
Assign spatial grids to the data (50x50km cells) 
```{r}
# Create an equal albers datum 
crs_1 <- "+proj=aea +lat_1=20 +lat_2=60 +lat_0=40 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80 +datum=NAD83 +units=m"
# Convert the data into spatial 
bd_sf <- st_as_sf(bd,
                  coords = c("decimalLongitude", "decimalLatitude"),
                  crs = "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs",
                  remove = FALSE)
fld_sf <- st_as_sf(fld,
                  coords = c("decimalLongitude", "decimalLatitude"),
                  crs = "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs",
                  remove = FALSE)
bd_sf <- bd_sf %>% 
  st_transform(crs = st_crs(crs_1)) # transform spatial bee data to that of equal albers
fld_sf <- fld_sf %>% 
  st_transform(crs = st_crs(crs_1)) 

sonoran_shp <- st_transform(sonoran_shp, crs = crs_1)

# Assign grids to the sonoran desert 
grid_1 <- st_make_grid(extent(sonoran_shp), cellsize = 50*1000, square = TRUE) %>% # 50x50km sq grids
  st_as_sf(crs = crs_1) %>% # Assign CRS as equal albers
  dplyr::mutate(GID = row_number()) # Track Grid IDs by row number in our datatable

touching_cells <- grid_1[sonoran_shp,] # define the cells that touch the shapefile 

# Plot out 
ggplot() + 
  geom_sf(sonoran_shp, mapping = aes(), fill = "darkorange") +
  geom_sf(touching_cells, mapping = aes(), alpha = 0.2) +
  theme_bw() +
  ggtitle("50x50km Grids over the Sonoran Desert")

# Assign bee data to 50x50 grid bins
grids_w_bees <- touching_cells %>% 
    st_join(bd_sf) %>% # 
    group_by(GID) %>% # Group by the grid ID
    mutate(point_count = case_when(is.na(scientificName) ~ 0,
                                   TRUE ~ 1)) %>% # Assign cells that dont have anything present with 0s 
    mutate(cell_count = sum(point_count)) # Sum up the number of specimens found in each grid cell (w/buffer)

grids_w_plants <- touching_cells %>% 
    st_join(fld_sf) %>% # 
    group_by(GID) %>% # Group by the grid ID
    mutate(point_count = case_when(is.na(scientificName) ~ 0,
                                   TRUE ~ 1)) %>% # Assign cells that dont have anything present with 0s 
    mutate(cell_count = sum(point_count)) # Sum up the number of specimens found in each grid cell (w/buffer)

# Plot out intensity 
grids_w_bees$cell_count <- ifelse(grids_w_bees$cell_count==0, NA, grids_w_bees$cell_count) # For ggplot purposes sub these 0s out to be NAs
grids_w_plants$cell_count <- ifelse(grids_w_plants$cell_count==0, NA, grids_w_plants$cell_count) # For ggplot purposes sub these 0s out to be NAs

ggplot(grids_w_bees) +
  geom_sf(mapping = aes(fill = (cell_count), alpha = 0.9)) + # Log Transform, correct for log10(1) = 0
    theme_bw() +
    scale_fill_gradientn(
      colours = colorRampPalette((RColorBrewer::brewer.pal(11, "YlOrRd")))(9), 
      na.value = "#808080" # The line that denotes NAs as grey
    ) +
     geom_sf(sonoran_shp, mapping = aes(), fill = NA) + # Adjusts fill to be NA
    ggtitle(paste0("Bee Observation Intensity all time")) +
    theme(axis.text.x = element_text(angle = 45, vjust = 0.5)) +
    #ggtitle("Bee Sampling Intensity 10x10km Grid") +
    theme(plot.title = element_text(hjust = 0.5)) +
    guides(fill=guide_legend(title="N Occurrences"))

ggplot(grids_w_plants) +
  geom_sf(mapping = aes(fill = (log(cell_count+1)), alpha = 0.9)) + # Log Transform, correct for log10(1) = 0
    theme_bw() +
    scale_fill_gradientn(
      colours = colorRampPalette((RColorBrewer::brewer.pal(11, "YlOrRd")))(9), 
      na.value = "#808080" # The line that denotes NAs as grey
    ) +
     geom_sf(sonoran_shp, mapping = aes(), fill = NA) + # Adjusts fill to be NA
    ggtitle(paste0("Plant Observations Intensity all time")) +
    theme(axis.text.x = element_text(angle = 45, vjust = 0.5)) +
    #ggtitle("Bee Sampling Intensity 10x10km Grid") +
    theme(plot.title = element_text(hjust = 0.5)) +
    guides(fill=guide_legend(title="log(N Occurrences+1)"))
```
Create temporal bins to look at continuity of sampling 
```{r}
# Calculate the % temporal coverage of each grid cell across all of the years 
year_range <- range(bd$year, na.rm = TRUE) # grab the range of years for the dataset
all_years <- seq(year_range[1], year_range[2]) # create a sequence across the min and max of our years

grids_w_bees <- grids_w_bees %>% 
  group_by(GID) %>% # Group by grid cell
  mutate(temp_cov_perc = sum(!is.na(unique(year)))/length(all_years)*100)
# Repeat process for the plants (should be identical year range)
year_range <- range(fld$year, na.rm = TRUE) # grab the range of years for the dataset
all_years <- seq(year_range[1], year_range[2]) # create a sequence across the min and max of our years

grids_w_plants <- grids_w_plants %>% 
  group_by(GID) %>% # Group by grid cell
  mutate(temp_cov_perc = sum(!is.na(unique(year)))/length(all_years)*100)
# 
ggplot(grids_w_bees) +
  geom_sf(mapping = aes(fill = (temp_cov_perc), alpha = 0.7)) + # Log Transform, correct for log10(1) = 0
    theme_bw() +
    scale_fill_gradientn(
      colours = colorRampPalette((RColorBrewer::brewer.pal(11, "BuPu")))(9), 
      na.value = "#808080" # The line that denotes NAs as grey
    ) +
     geom_sf(sonoran_shp, mapping = aes(), fill = NA) + # Adjusts fill to be NA
    ggtitle(paste0("Bee Observation Temporal Coverage")) +
    theme(axis.text.x = element_text(angle = 45, vjust = 0.5)) +
    #ggtitle("Bee Sampling Intensity 10x10km Grid") +
    theme(plot.title = element_text(hjust = 0.5)) +
    guides(fill=guide_legend(title="% of all time for 1950-1972"))

ggplot(grids_w_plants) +
  geom_sf(mapping = aes(fill = (temp_cov_perc), alpha = 0.7)) + # Log Transform, correct for log10(1) = 0
    theme_bw() +
    scale_fill_gradientn(
      colours = colorRampPalette((RColorBrewer::brewer.pal(11, "BuPu")))(9), 
      na.value = "#808080" # The line that denotes NAs as grey
    ) +
     geom_sf(sonoran_shp, mapping = aes(), fill = NA) + # Adjusts fill to be NA
    ggtitle(paste0("Plant Observation Temporal Coverage")) +
    theme(axis.text.x = element_text(angle = 45, vjust = 0.5)) +
    #ggtitle("Bee Sampling Intensity 10x10km Grid") +
    theme(plot.title = element_text(hjust = 0.5)) +
    guides(fill=guide_legend(title="% of all time for 1950-1972"))
```
Retain cells with greater than or equal to 75% Temporal Coverage (Arbitrary, question for Rob & JM)
```{r}
# Filter for high coverage grid cells
h_b_grids <- grids_w_bees %>% 
  filter(temp_cov_perc >= 75)
h_p_grids <- grids_w_plants %>% 
  filter(temp_cov_perc >= 75)

ggplot(h_b_grids) +
  geom_sf(mapping = aes(fill = (temp_cov_perc), alpha = 0.7)) + # Log Transform, correct for log10(1) = 0
    theme_bw() +
    scale_fill_gradientn(
      colours = colorRampPalette((RColorBrewer::brewer.pal(11, "BuPu")))(9), 
      na.value = "#808080" # The line that denotes NAs as grey
    ) +
     geom_sf(sonoran_shp, mapping = aes(), fill = NA) + # Adjusts fill to be NA
    ggtitle(paste0("Bee Observation Temporal Coverage for high temporal coverage cells")) +
    theme(axis.text.x = element_text(angle = 45, vjust = 0.5)) +
    #ggtitle("Bee Sampling Intensity 10x10km Grid") +
    theme(plot.title = element_text(hjust = 0.5)) +
    guides(fill=guide_legend(title="% of all time for 1950-1972"))

ggplot(h_p_grids) +
  geom_sf(mapping = aes(fill = (temp_cov_perc), alpha = 0.7)) + # Log Transform, correct for log10(1) = 0
    theme_bw() +
    scale_fill_gradientn(
      colours = colorRampPalette((RColorBrewer::brewer.pal(11, "BuPu")))(9), 
      na.value = "#808080" # The line that denotes NAs as grey
    ) +
     geom_sf(sonoran_shp, mapping = aes(), fill = NA) + # Adjusts fill to be NA
    ggtitle(paste0("Plant Observation Temporal Coverage for high temporal coverage cells")) +
    theme(axis.text.x = element_text(angle = 45, vjust = 0.5)) +
    #ggtitle("Bee Sampling Intensity 10x10km Grid") +
    theme(plot.title = element_text(hjust = 0.5)) +
    guides(fill=guide_legend(title="% of all time for 1950-1972"))

# And collapse to the same grid cells of shared high temporal coverage for both datasets
bee_cells <- unique(h_b_grids$GID)
plant_cells <- unique(h_p_grids$GID)
# intersect
shared_cells <- intersect(bee_cells, plant_cells)
# filter
h_p_grids <- h_p_grids %>% 
  filter(GID %in% shared_cells)
h_b_grids <- h_b_grids %>%  
  filter(GID %in% shared_cells)

ggplot(h_b_grids) +
  geom_sf(mapping = aes(fill = (temp_cov_perc), alpha = 0.7)) + # Log Transform, correct for log10(1) = 0
    theme_bw() +
    scale_fill_gradientn(
      colours = colorRampPalette((RColorBrewer::brewer.pal(11, "BuPu")))(9), 
      na.value = "#808080" # The line that denotes NAs as grey
    ) +
     geom_sf(sonoran_shp, mapping = aes(), fill = NA) + # Adjusts fill to be NA
    ggtitle(paste0("Bee Observation Temporal Coverage for shared high temporal coverage cells")) +
    theme(axis.text.x = element_text(angle = 45, vjust = 0.5)) +
    #ggtitle("Bee Sampling Intensity 10x10km Grid") +
    theme(plot.title = element_text(hjust = 0.5)) +
    guides(fill=guide_legend(title="% of all time for 1950-1972"))
ggplot(h_p_grids) +
  geom_sf(mapping = aes(fill = (temp_cov_perc), alpha = 0.7)) + # Log Transform, correct for log10(1) = 0
    theme_bw() +
    scale_fill_gradientn(
      colours = colorRampPalette((RColorBrewer::brewer.pal(11, "BuPu")))(9), 
      na.value = "#808080" # The line that denotes NAs as grey
    ) +
     geom_sf(sonoran_shp, mapping = aes(), fill = NA) + # Adjusts fill to be NA
    ggtitle(paste0("Plant Observation Temporal Coverage for shared high temporal coverage cells")) +
    theme(axis.text.x = element_text(angle = 45, vjust = 0.5)) +
    #ggtitle("Bee Sampling Intensity 10x10km Grid") +
    theme(plot.title = element_text(hjust = 0.5)) +
    guides(fill=guide_legend(title="% of all time for 1950-1972"))

```
Check temporal coverage per given cell per group 
```{r}
# Drop the geometry field for quicker processing 
hbg <- h_b_grids %>% 
  st_drop_geometry()
hpg <- h_p_grids %>% 
  st_drop_geometry()

# Construct a time series faceted by Grid Cell
ggplot(hbg, aes(x = factor(year))) +
  geom_bar(fill = "darkorange", stat = "count", position = "dodge") +
  geom_text(stat = "count", aes(label = ..count..),
            position = position_dodge(width = 0.9), hjust = -0.75 , angle = 90, size = 3) +
  labs(title = "Number of Records per Year",
       x = "Year",
       y = "Density") +
  theme_minimal() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_wrap(~ GID)

# Construct a time series faceted by Grid Cell
ggplot(hpg, aes(x = factor(year))) +
  geom_bar(fill = "darkgreen", stat = "count", position = "dodge") +
  geom_text(stat = "count", aes(label = ..count..),
            position = position_dodge(width = 0.9), hjust = -0.75 , angle = 90, size = 3) +
  labs(title = "Number of Records per Year",
       x = "Year",
       y = "Density") +
  theme_minimal() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_wrap(~ GID)
```

Create doy distributions per year 
```{r}
year_range <- range(hbg$year, na.rm = TRUE) # grab the range of years for the dataset
all_years <- seq(year_range[1], year_range[2]) # create a sequence across the min and max of our years
doy_plot_dir <- "/home/jt-miller/Gurlab/sliding-phenology/outputs/doy-by-year-plots/"
x <- list()
for(i in 1:length(all_years)){
  
  # Filter to year of interest
  y <- hbg %>% 
    filter(year == all_years[[i]])  
  if(nrow(y) == 0){
    next
  }
  # Plot it 
  x <- ggplot(data = y, aes(x = doy)) +
    geom_histogram(bins = 250) +
    labs(
      x = "Day of Year",
      y = "Number of Individuals",
      title = paste0(all_years[[i]])
    ) +
     scale_y_continuous(expand = c(0,0)) +   
     scale_x_continuous(limits = c(0,365)) +
     theme_classic() +
     theme(plot.title = element_text(hjust = 0.5)) + 
    facet_wrap( ~ GID)
  ggsave(x, file=paste0(doy_plot_dir, "bees-doy-plot-", all_years[[i]],".png"), width = 14, height = 18, units = "cm")
}
# Repeat for plants
year_range <- range(hpg$year, na.rm = TRUE) # grab the range of years for the dataset
all_years <- seq(year_range[1], year_range[2]) # create a sequence across the min and max of our years
doy_plot_dir <- "/home/jt-miller/Gurlab/sliding-phenology/outputs/doy-by-year-plots/"
x <- list()
for(i in 1:length(all_years)){
  
  # Filter to year of interest
  y <- hpg %>% 
    filter(year == all_years[[i]])  
  if(nrow(y) == 0){
    next
  }
  # Plot it 
  x <- ggplot(data = y, aes(x = doy)) +
    geom_histogram(bins = 250) +
    labs(
      x = "Day of Year",
      y = "Number of Individuals",
      title = paste0(all_years[[i]])
    ) +
     scale_y_continuous(expand = c(0,0)) +   
     scale_x_continuous(limits = c(0,365)) +
     theme_classic() +
     theme(plot.title = element_text(hjust = 0.5)) + 
    facet_wrap( ~ GID)
  ggsave(x, file=paste0(doy_plot_dir, "plants-doy-plot-", all_years[[i]],".png"), width = 14, height = 18, units = "cm")
}
```














Divide each species up into its own dt 
```{r}
b_sp_dts <- list()
b_sp_v <- unique(bd$scientificName)
for(i in 1:length(b_sp_v)){
  b_sp_dts[[i]] <- subset(bd, scientificName %in% b_sp_v[[i]])
    
}
```



