---
title: "taxonomic-harmonization"
author: "jt-miller"
date: "2023-12-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Harmonization of the Taxonomic Names for Plants

Load Dependencies 
```{r}
library(data.table)
library(tidyverse)
library(rgnparser)
library(magrittr)
library(stringr)
library(sqldf)
library(WorldFlora)
library(bdc)
```

Load Plant Data & WFO backbone
```{r}
plants <- fread("/home/jt-miller/Gurlab/sliding-phenology/data/processed/sonoran-flowering-temporal-labeled-data.csv")
plants_og <- plants 
plant_cols <- names(plants)
```


```{r}
parse_names <- bdc_clean_names(plants$scientificName)
parse_names <- parse_names %>%  
  dplyr::select(.uncer_terms, names_clean)
plants <- dplyr::bind_cols(plants, parse_names)

query_names <- bdc_query_names_taxadb(
  sci_name            = plants$names_clean,
  replace_synonyms    = TRUE, # replace synonyms by accepted names?
  suggest_names       = TRUE, # try to found a candidate name for misspelled names?
  suggestion_distance = 0.9, # distance between the searched and suggested names
  db                  = "gbif", # taxonomic database
  rank_name           = "Plantae", # a taxonomic rank
  rank                = "kingdom", # name of the taxonomic rank
  parallel            = FALSE, # should parallel processing be used?
  ncores              = 2, # number of cores to be used in the parallelization process
  export_accepted     = FALSE # save names linked to multiple accepted names
)

plants <-
  plants %>%
  dplyr::rename(verbatim_scientificName = scientificName) %>%
  dplyr::select(-names_clean) %>%
  dplyr::bind_cols(., query_names)

report <-
  bdc_create_report(data = plants,
                    database_id = "database_id",
                    workflow_step = "taxonomy",
                    save_report = FALSE)

report

cols_of_interest <- names()
plants_harmonized <- plants %>% 
  filter(!is.na(scientificName)) %>% 
  select(all_of(plant_cols))


fwrite(plants_harmonized, "/home/jt-miller/Gurlab/sliding-phenology/data/processed/harmonized_plants.csv")
```





